pipeline {
    agent { 
        label 'CFCDSLVJ'
    }

    stages {
        stage('Build') { 
            steps { 
                bat 'cmd /c echo Build'
            }
        }
        stage('Test'){
            steps {
                bat 'cmd /c echo Test'
            }
        }
        stage('Deploy') {
            steps {
                bat 'cmd /c echo Deploy'
            }
        }
    }
}